const SystemType = {
    NEUTRON_STAR: 'NEUTRON_STAR',
    RED_STAR: 'RED_STAR',
    ORANGE_STAR: 'ORANGE_STAR',
    BLUE_STAR: 'BLUE_STAR',
    YOUNG_STAR: 'YOUNG_STAR',
    WHITE_DWARF: 'WHITE_DWARF',
    BLACK_HOLE: 'BLACK_HOLE',
    HYPERGIANT: 'HYPERGIANT',
    NEBULA: 'NEBULA',
    UNSTABLE: 'UNSTABLE',
};

const WaypointType = {
    PLANET: 'PLANET',
    GAS_GIANT: 'GAS_GIANT',
    MOON: 'MOON',
    ORBITAL_STATION: 'ORBITAL_STATION',
    JUMP_GATE: 'JUMP_GATE',
    ASTEROID_FIELD: 'ASTEROID_FIELD',
    ASTEROID: 'ASTEROID',
    ENGINEERED_ASTEROID: 'ENGINEERED_ASTEROID',
    ASTEROID_BASE: 'ASTEROID_BASE',
    NEBULA: 'NEBULA',
    DEBRIS_FIELD: 'DEBRIS_FIELD',
    GRAVITY_WELL: 'GRAVITY_WELL',
    ARTIFICIAL_GRAVITY_WELL: 'ARTIFICIAL_GRAVITY_WELL',
    FUEL_STATION: 'FUEL_STATION',
};

const Factions = {
    COSMIC: 'COSMIC',
    VOID: 'VOID',
    GALACTIC: 'GALACTIC',
    QUANTUM: 'QUANTUM',
    DOMINION: 'DOMINION',
    ASTRO: 'ASTRO',
    CORSAIRS: 'CORSAIRS',
    OBSIDIAN: 'OBSIDIAN',
    AEGIS: 'AEGIS',
    UNITED: 'UNITED',
    SOLITARY: 'SOLITARY',
    COBALT: 'COBALT',
    OMEGA: 'OMEGA',
    ECHO: 'ECHO',
    LORDS: 'LORDS',
    CULT: 'CULT',
    ANCIENTS: 'ANCIENTS',
    SHADOW: 'SHADOW',
    ETHEREAL: 'ETHEREAL',
};

module.exports = { SystemType, WaypointType, Factions };
